version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - 443:80
    depends_on:
      - php
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d
    restart: always
    networks:
      - laravel-net

  php:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    image: php_laravel:1.0
    restart: always
    depends_on:
      - db
      - redis
    volumes: 
      - ./src:/var/www
    networks:
      - laravel-net
  
  db:
    image: mysql:latest
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secrete
    networks:
      - laravel-net

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge